#!/usr/bin/env bash
set -ex

# shellcheck disable=SC2046
cd $(dirname "$0")/..

source ./scripts/version.sh

DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker image build \
    --build-arg TAG="${VERSION}" \
    --build-arg KUBERNETES_VERSION="${KUBERNETES_VERSION}" \
    --build-arg MAJOR="${VERSION_MAJOR}" \
    --build-arg MINOR="${VERSION_MINOR}" \
    --build-arg CACHEBUST="$(date +%s%N)" \
    --tag "${REPO}"/"${PROG}"-windows-runtime:"${DOCKERIZED_VERSION}" \
    --tag "${REPO}"/"${PROG}"-windows-runtime:"${DOCKERIZED_VERSION}"-"${GOARCH}" \
    --target windows-runtime \
.

mkdir -p build/images
docker image save \
    --output build/images/"${PROG}"-windows-runtime.tar \
    "${REPO}"/"${PROG}"-windows-runtime:"${DOCKERIZED_VERSION}" \
    "${REPO}"/"${PROG}"-windows-runtime:"${DOCKERIZED_VERSION}"-"${GOARCH}"
